### ISSUE TITLE
Update ICD and CHOP catalogs for search API

### ISSUE THREAD

**Issue by SamJa** [eonum/medcodelogic-frontend#1]
Missing ICD10-GM 2008 catalog and missing CHOP catalogs below year 2014.

**Comment by tschimbr** [comment]
Please specify what exactly is missing or just copy the mail.

**Comment by SamJa** [comment]
Uns ist beim letzten Usability Test aufgefallen, dass bei der Navigation auf der Startseite keine Titel für die Elemente für ICD 2008 angezeigt werden.

Die eonum API liefert nur null-Werte für die entsprechenden Elemente des Katalogs. Bsp:

https://search.eonum.ch/de/icds/ICD10-GM-2008/C09?show_detail=1

Eine weitere Angegelegenheit, die im Usability Test rausgefunden wurde:

Die API von eonum vor bei Einträgen vor 2014 bei der Abfrage des CHOPS Root Element also z.B.

https://search.eonum.ch/de/chop_chapters/CHOP_2012/CHOP_2012?show_detail=1

gibt keine Children Elemente zurück. Ab 2014 stimmt es dann:

https://search.eonum.ch/de/chop_chapters/CHOP_2014/CHOP_2014?show_detail=1

**Comment by tschimbr** [comment]
This issue is in the wrong repo. See: https://github.com/eonum/medcodesearch/issues/16
